### ISSUE TITLE
Rewrite yaml file using ChatGPT to ensure it's working

### ISSUE THREAD

**Issue by dennisccastro** [dennisccastro/ActionsAssignment#4]
The yaml file is failing. Will use AI to write a yaml file that works

**Comment by dennisccastro** [comment]
I've spent a lot of time on this and I still keep getting failures.

**Comment by dennisccastro** [comment]
Used ChatGPT to generate a yaml file but it still isn't working.

**Comment by dennisccastro** [comment]
Success! The yaml file is running with no errors!

**Comment by dennisccastro** [comment]
I was able to write a functioning yaml file using AI.

**Comment by planetoftheweb** [comment]
Looks like the last run of this was successful. Did you figure it out?

**Comment by dennisccastro** [comment]
> Looks like the last run of this was successful. Did you figure it out?

Well, the AI figured it out, actually. I used ChatGPT to generate the yml file and when I deployed it, I kept getting failures. I inquired about the specific errors using ChatGPT. Eventually, I had to create a token and also had to change some read/write permissions on the repo to make it work. Couldn't have done it without the AI.
